### ISSUE TITLE
Other - Update Plugin details and images at Chrome Store

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#23]
**Issue description:**

The add-on on the [Chrome Store](https://chrome.google.com/webstore/detail/hubcare/oilkenamijbelpchecmfpllponcmlcbm?hl=pt-BR) is with a Lorem Ipsum description. It needs to be updated to some text that explains in a few words what is the add-on and how to use it.

Besides that, some images aren't exactly awesome. Let's fix it :smiley:

**Comment by cjjcastro** [comment]
This can be changed in the file: https://github.com/fga-eps-mds/2019.1-hubcare-plugin/blob/master/app/_locales/en/messages.json

**Comment by filipetoyoshima** [comment]
I've updated the text on the branch 23, but not all setups are available via the indicated file. We need to go to Chrome Store's settings to update this.
