### ISSUE TITLE
Feature - Create a Tab button on GitHub

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#25]
## **Is your feature request related to a problem? Please describe.**
We need some space on GitHub to render all the info we want to show to the users. This space must respect the user's interface, so it must only be activated through a button.

## **Describe the solution you'd like**
Put a **button** on the GitHub repo page, just like as all the tab buttons that already exist. It must look pretty like ZenHub button. Also, a [Prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/) defines (more or less) how this button should look like, it doesn't need to be just equal the prototype, is just more like an idea.

The GitHub visual identity must be respected.

## **Additional context**
To have a better understanding of how and why it is needed, see [Vision Document](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/vision-document/)

## Acceptance Criteria
- [ ] Render a new tab button on GitHub repo
- [ ] Put a monochromatic logo of HubCare on the button

**Comment by cjjcastro** [comment]
The class of buttons that GitHub uses is reponav-item

**Comment by vitorAlves7** [comment]
The button still does not have the image because it has to change the permissions of the manifest, however we will think about the best way to do this.

**Comment by filipetoyoshima** [comment]
#33 solve this
