### ISSUE TITLE
Feature - Info Popup

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#26]
**Is your feature request related to a problem? Please describe.**
The user must have an on-hand guide to know about what the plugin does.

**Describe the solution you'd like**
We have some unused space on the browser's plugin button, which, now, renders a useless popup. It can be used to show to the user some brief synopsis about what each badge means.

A low-level prototype:

![image](https://user-images.githubusercontent.com/29482983/57668521-0050de00-75de-11e9-93c3-f9d1c8ab744f.png)

**Acceptance Criteria**

- [x] Logo at the upper left corner
- [x] Activate / deactivate switch at the upper right corner
- [x] Three columns of text, one for each badge
- [x] "Star Us" button that links this repository
- [x] A text that asks the user to go to a GitHub page (if not yet)
- [x] Respect to the HubCare's visual Identity.

**Comment by Brian2397** [comment]
Does anyone have a look at the PR, please?
to see if everything is all right
