### ISSUE TITLE
Feature - Clean the GitHub Page and put some content there

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#28]
## Problem Related
We need some space on GitHub to render all the info we want to show to the users. This space must respect the user's interface, so it must only be activated through a button.

## **Describe the solution you'd like**
When clicking at the button described on #25, clean all the content below tabs and put our badges there. When clicking at another tab, the content must be restored.

## **Additional context**
To have a better understanding of how and why it is needed, see [Vision Document](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/vision-document/)

## Acceptance Criteria
- [x] Clean page when clicking button
- [x] Put badges on cleaned space
- [x] Restore content when clicking at another tab
- [ ] Test coverage at 80%

**Comment by cjjcastro** [comment]
To solve this issue we need the button to put the click action to delete the elements of the page. Issue # 37 proposes to create the button in a new place of the screen, as there is no button yet what should I do, since the method to clean the page is ready

**Comment by filipetoyoshima** [comment]
The button is there. It was created with #33.
Just create the script to clean the screen. When #37 is being done, just transfer the created method to the new button.

**Comment by cjjcastro** [comment]
We were able to create a method that removes the elements from the screen and inserts the badges in place. The only problem we found was that we need to open the page in a new tab, since chrome does not allow injecting JS code into screen elements.

**Comment by cjjcastro** [comment]
I was able to create the click event to remove elements from the screen like this:
```
var hubbutton = document.getElementById('hubcare-button');
hubbutton.addEventListener("click", function() {
    cleanPageContent()
}, false);
```
