### ISSUE TITLE
Commit by week graph on Hubcare's space on GitHub

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#35]
**Is your feature request related to a problem? Please describe.**
To describe in details the metrics calculated on HubCares, the user may want some visual and historical data. One of the metrics is the commits that happen on the repository.

**Describe the solution you'd like**
To provide a fast and visual way of getting commit by week, it is interesting having a graph that shows the progress of this data along the last 10 weeks.

**Describe alternatives you've considered**
Maybe 10 weeks may be more, or maybe less than the optimal sample. We can check on the next Acceptation test.

**Additional context**
Some inspiration may be found in [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/).

**Obs**: #42 has merged when there was no commit report on the production of API. This issue was closed with mocked data. Some other issue will be created to use real data.

**Comment by Brian2397** [comment]
Is it possible to request data from the API commits?

**Comment by filipetoyoshima** [comment]
Now I'm seeing that not yet. API complete report isn't on production yet.
Well, you guys showed the viability of this implementation and I believe that is enough to close the issue cause put some real data will be a piece of cake.

But, I want some other point of view. Since @cjjcastro has participated in this branch, I would like @RomuloSouza's and @Hiroshi18's opinion.

**Comment by cjjcastro** [comment]
Como a parte da API está em desenvolvimento, resolvemos criar com dados estáticos e de uma maneira bem estruturada para inserir os dados reais assim que estiverem disponíveis.

**Comment by RomuloSouza** [comment]
You're right, it's not possible to request this data from the API yet. This issue has to be done with mock data, and I think it's ok to accept taking this into consideration @filipetoyoshima

**Comment by filipetoyoshima** [comment]
Ok. Some other issue will be created to pull real data from API.
