### ISSUE TITLE
BUG - Change render locations of HubCare elements on GitHub

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#37]
## **Is your feature request related to a problem? Please describe.**
Rendering the badges below tab buttons is causing some rendering problems. GitHub doesn't reload the entire page when changing tabs as expected. It is not exactly known how things below tabs buttons are rendered, so altering it may cause some future problems.

## **First Idea of Solution (Deprecated)**
To avoid those render problems, a solution may change the locations of the elements. **Rendering above tab buttons** instead of below may solve the problems we are having.

Also, **the Hubcare tab button has to be changed too** due to those rendering problems. It can be a link or a button aside of badges since we're not using tab buttons anymore.

## **Used Solution**
It was possible and simple to avoid problems when changing tabs on GitHub.

##Acceptance Criteria
- [x] HubCare badges have to keep showing on other GitHub tabs. Add-on tabs, such as ZenHub, don't need to be included.
- [x] HubCare tab button can't vanish after selecting other GitHub tabs.

**Comment by cjjcastro** [comment]
changing the rendering location did not solve the problem, I'll try to use jquery. I've found a way that can work:
```
$(document).on('pjax:complete', () => {
   myFunction();
});
```
With this I can call a function that loads the badges again

**Comment by filipetoyoshima** [comment]
> changing the rendering location did not solve the problem, I'll try to use jquery. I've found a way that can work:
> 
> ```
> $(document).on('pjax:complete', () => {
>    myFunction();
> });
> ```
> 
> With this I can call a function that loads the badges again

Oh, boy...

if this works, you think that change badge locations still necessary?

**Comment by cjjcastro** [comment]
I do not think it's necessary

**Comment by filipetoyoshima** [comment]
Okay. Then I will limit this issue scope to the bug fix and you can solve this with you think is best.
Keep us in touch about the resolution.

**Comment by cjjcastro** [comment]
Okay
