### ISSUE TITLE
Refactor - Change the fonts of badges

### ISSUE THREAD

**Issue by cjjcastro** [fga-eps-mds/2019.1-hubcare-plugin#40]
**Is your feature request related to a problem? Please describe.**
The font used in badges is not very nice compared to the fonts used in github, it is very different.

**Describe the solution you'd like**
In the document of the [visual identity](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/visual-identity/) the typography is proposed, I suggest to modify the configurations of the badges to use the defined fonts.

**Additional context**
The badges are currently like this:
![image](https://user-images.githubusercontent.com/26393787/58181980-2a13a000-7c83-11e9-8032-413cf732d233.png)

**Comment by cjjcastro** [comment]
https://github.com/hmil/project-badge

**Comment by Brian2397** [comment]
We're just getting the source: Arial.

**Comment by filipetoyoshima** [comment]
This was solved within #86
