### ISSUE TITLE
Refactor - Get real data for the commits Graph

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#44]
## Related Problem
Actually, commits graph are using some mocked data.

## Purposed Solution
Now, API is returning a complete report with the commits number in the last 10 weeks.

## Aditional Context
_Originally posted by @filipetoyoshima in https://github.com/fga-eps-mds/2019.1-hubcare-plugin/issues/35#issuecomment-495961344_

## Acceptance Criteria
- [x] Use real data on commit graph.

**Comment by vitorAlves7** [comment]
To accomplish this issue we need the link with the data related to the commits per week, and we noticed that there were changes made devel, for evaluating the [Devel #48](https://github.com/fga-eps-mds/2019.1-hubcare-plugin/pull/48)

**Comment by filipetoyoshima** [comment]
> To accomplish this issue we need the link with the data related to the commits per week, and we noticed that there were changes made devel, for evaluating the Update master #91 in API

Done!

**Comment by vitorAlves7** [comment]
We obtained the API data is returning a complete report with the number of commits of the last 10 weeks.
![Captura de tela de 2019-06-02 00-13-01](https://user-images.githubusercontent.com/43835325/58756267-4e654d00-84cb-11e9-876d-a2a505a963ae.png)

**Comment by FranciscoHeronildo** [comment]
However, when we update the HubCare tab page, a graph without values is returned, as it has not yet completed the data request.

![graph_bad](https://user-images.githubusercontent.com/30841230/58756320-9df84880-84cc-11e9-8f04-867983cdb56d.png)

What is the best possible solution to reverse this problem? With a loading in the HubCare tab or disable the HubCare tab until complete data request is complete.

**Comment by filipetoyoshima** [comment]
> However, when we update the HubCare tab page, a graph without values is returned, as it has not yet completed the data request.
> 
> ![graph_bad](https://user-images.githubusercontent.com/30841230/58756320-9df84880-84cc-11e9-8f04-867983cdb56d.png)
> 
> What is the best possible solution to reverse this problem? With a loading in the HubCare tab or disable the HubCare tab until complete data request is complete.

This will be fixed in another issue. It is a more complex fix that may affect many other renders at HubCare tab.

**Comment by FranciscoHeronildo** [comment]
Thanks man
