### ISSUE TITLE
Refactor - Style HubCare button as a GitHub tab button

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#46]
## **Is your feature request related to a problem? Please describe.**
The HubCare tab button is rendered as a simple text, it does not behave like a button, as it should do.

## **Describe the solution you'd like**
The tab button has some characteristics, as a hover interaction, a specific style when selected and interact with the user's cursor in such way user can know that it is a button.

## Acceptance Criteria
- [x] Monochromatic HubCare icon on the button
- [x] Correct interactions with the cursor
- [x] Style when selected just as other GH tab buttons
- [x] Remove "selected" style when clicking on another tab button
- [x] Remove "selected" style from other buttons when selecting HubCare
- [x] Maintain the actual script to clean the screen

**Comment by filipetoyoshima** [comment]
I'll make an icon that fits on GitHub tab buttons pattern

**Comment by filipetoyoshima** [comment]
> I'll make an icon that fits on GitHub tab buttons pattern

Done!

**Comment by cjjcastro** [comment]
To remove "selected" style from other buttons when selecting HubCare, use remove class method. Like this:

```
a = document.getElementsByClassName("js-selected-navigation-item selected")[0]
a.classList.remove("selected")
```

**Comment by FranciscoHeronildo** [comment]
ok man. Thanks.

**Comment by vitorAlves7** [comment]
ok man, thanks
