### ISSUE TITLE
Feature - PR Quality Graph Model

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#58]
## **Is your feature request related to a problem? Please describe.**
At the last pivoting, users asked for a more complete report of the data. The team has created some visual representation of the required data.

## **Describe the solution you'd like**
According to [Prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/), a bar graph that shows how many PRs of the sample are in each category. The categories must be explained.

The [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/) shows a table as the horizontal index of the graph. This is the ideal, but maybe not possible. Any way of correlating each category (and explain it) with correspondent bar may be considered as a solution.

## **Describe alternatives you've considered**
Another way of showing the data may be considered since the Acceptance Criteria is satisfied.

## **Additional context**
The [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype) can be used as a visual guide.

## Acceptance Criteria
- [x] A visual way of fastly understanding the proportion of PRs in each category. Bar graph recommended.
- [x] Tooltip on the graph that shows the number that means each bar.
- [x] Associate each bar with a category.

**Comment by cjjcastro** [comment]
I used pie chart as shown in the picture:

![image](https://user-images.githubusercontent.com/26393787/59155258-98b27500-8a5b-11e9-8427-1a8b32c47d49.png)
