### ISSUE TITLE
Feature - "Check" Model for the Report

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#59]
## **Is your feature request related to a problem? Please describe.**
At the last pivoting, users asked for a more complete report of the data. The team has created some visual representation of the required data.

## **Describe the solution you'd like**
According to [Prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/), a lot of checks have to be shown.

To avoid code duplication, we need a function that receives the title, a boolean value, and tooltip text as parameters and inserts on the HTML document a check with the desired values.

## **Describe alternatives you've considered**
Another way of showing the data may be considered since the Acceptance Criteria is satisfied.

## **Additional context**
The [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype) can be used as a visual guide.

**Example:**
![image](https://user-images.githubusercontent.com/29482983/58830444-b7aaa480-8620-11e9-9229-882f50e21ac0.png)

## Acceptance Criteria
- [x] Render the title on style defined [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype)
- [x] Render a :heavy_check_mark:  if the received boolean is true
- [x] Render a :x: if the received boolean is false

To validation purpose, please, include two calls of the function, one with true e one with false.

**Comment by FranciscoHeronildo** [comment]
Hi man, we need the svg of the check and close mark to proceed with what is asked in the issue.

**Comment by FranciscoHeronildo** [comment]
The booleans were mock at line 248 of the contentscript.js file
`createCheckModel (true)` so an SVG with a check mark is shown
![check](https://user-images.githubusercontent.com/30841230/58849830-66230980-8662-11e9-9a7c-6ff669a42b2c.png)
`createCheckModel (false)` so an SVG with the closing mark is shown
![closed](https://user-images.githubusercontent.com/30841230/58849853-7935d980-8662-11e9-847e-179e0c536041.png)

**Comment by filipetoyoshima** [comment]
> Hi man, we need the svg of the check and close mark to proceed with what is asked in the issue.

Committed! :wink:

**Comment by FranciscoHeronildo** [comment]
Thanks man.
