### ISSUE TITLE
Feature - Tooltip render method

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#60]
## **Is your feature request related to a problem? Please describe.**
At the last pivoting, users asked for a more complete report of the data. The team has created some visual representation of the required data. That visual representation has a lot of charts that may be confusing.

## **Describe the solution you'd like**
According to [Prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/), every chart must have a tooltip that is rendered aside from the graph title.

To avoid code duplication, we need a function that receives the tooltip message as parameter and inserts on the HTML document a :?: with the desired values.

## **Describe alternatives you've considered**
Another way of showing the data may be considered since the Acceptance Criteria is satisfied.

## **Additional context**
The [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype) can be used as a visual guide.

**Example:**
![Screenshot from 2019-06-03 17-19-43](https://user-images.githubusercontent.com/29482983/58832033-6b616380-8624-11e9-979f-dfe1e18b19c8.png)

## Acceptance Criteria
- [x] Render a :question: icon wherever it is called
- [x] Render the help message when hovering
- [x] Follow the style purposed by the [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype) and / or the GitHub visual identity.

**Comment by Brian2397** [comment]
We need the SVG of the question icon to proceed with what is asked in the issue.

**Comment by filipetoyoshima** [comment]
Done!

**Comment by Brian2397** [comment]
We tried use the <img> for SVG.
But the tag <img> dont support SVG image

**Comment by Brian2397** [comment]
We were able to use the img tag to use IMG.

Function used:
chrome.extension.getURL ("../ images / questionMark.svg")

For this it was necessary to add the SVG image in the manifest:
"web_accessible_resources": [
    "images / questionMark.svg"
  ]
