### ISSUE TITLE
Feature - Loading Message

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-plugin#87]
## **Is your feature request related to a problem? Please describe.**
The analysis that the API does on a repo may take a while. So, it takes some time to render the badges, which may make the user frustrated and even think that the plugin isn't working, which is not true.

## **Describe the solution you'd like**
To calm down the user, we need a message that explains why it may take so long. This message should be shown along with the loading animation

**Also**

Please, change the loading image. It occupies more space than the badges, so, when the image fades out, all the page is shifted up.

## **Message Suggestion**
> Você foi a primeira pessoa a analisar esse repositório hoje! Estamos fazendo as contas para você :wink: Demora menos que um minuto.

## Acceptance Criteria
- [x] Message is shown when the badges are loading
- [x] Typography according to [Visual Guidelines](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/#diretrizes-visuais-para-o-hubcare-no-github)
- [x] Loading animation with the same hight of the badges

**Comment by vitorAlves7** [comment]
![photo_2019-06-19_23-33-28](https://user-images.githubusercontent.com/43835325/59814167-b8169100-92ea-11e9-842e-224b9f90e019.jpg)
 
Changed the style of loading and its animation. What do you think?
